package kodi

import (
	"github.com/agnivade/levenshtein"
	"sort"
	"strings"
)

type SearchResult struct {
	ID    string
	Name  string
	Score int
}

type AnimeEntry struct {
	ID   string
	Name string
}

// A harfi katta bo'lishi shart
var AnimeList = []AnimeEntry{
	{ID: "1", Name: "Vanpis"},
	{ID: "2", Name: "Naruto"},
	{ID: "3", Name: "Iblislar qotili"},
	{ID: "4", Name: "Franksdagi sevgi"},
	{ID: "5", Name: "Daho shahzodani mamlakatni qutqargani haqida"},
	{ID: "6", Name: "Xarobalar qiroligi"},
	{ID: "7", Name: "Soyada kotarilish"},
	{ID: "8", Name: "Tokiyo qasoskorlari"},
	{ID: "9", Name: "Titanlar hujumi"},
	{ID: "10", Name: "Jodugarlar jangi"},
	{ID: "11", Name: "Qalqon qahromoni"},
	{ID: "12", Name: "Sharlota"},
	{ID: "13", Name: "Qoshni farishta"},
	{ID: "14", Name: "yolg'izlikda daraja ko'taish"},
	{ID: "15", Name: "Aliya bazan mega rustilida nos karashma qiladi"},
	{ID: "16", Name: "Davolovchi qahramon"},
	{ID: "17", Name: "So'ngi serafim"},
	{ID: "18", Name: "Basketbol Kuroko"},
	{ID: "19", Name: "Ochkoz bersek"},
	{ID: "20", Name: "Zombi 100"},
	{ID: "21", Name: "Nomsiz Xotira"},
	{ID: "22", Name: "Qotil Akame"},
	{ID: "23", Name: "Jahannam jannati"},
	{ID: "24", Name: "Qora Klever"},
	{ID: "25", Name: "Vanitas xotiralari"},
	{ID: "26", Name: "Bleach"},
	{ID: "27", Name: "O‘lmas qirolning kundalik hayoti"},
	{ID: "28", Name: "Qora o'q"},
	{ID: "29", Name: "Men Muvaffaqiyatsiz..."},
	{ID: "30", Name: "Sakamoto Kunlari"},
	{ID: "31", Name: "Tungi Boyqushlar Kuyi"},
	{ID: "32", Name: "Zulmat Iblisi"},
	{ID: "33", Name: "Qahramon Boʻlish X"},
	{ID: "34", Name: "Yozukura Oilasi"},
	{ID: "35", Name: "Zulmat Farzandi"},
	{ID: "36", Name: "Qudrat! Yangi Hikoya"},
	{ID: "37", Name: "Yangi Saga"},
	{ID: "38", Name: "Uyatchang Qahramon va Qotil Malikalar"},
	{ID: "39", Name: "Doktor stoun"},
	{ID: "40", Name: "Taxt muxri"},
	{ID: "41", Name: "Badargʻa qilingan qahramon"},
	{ID: "42", Name: "Boshqa dunyodan muammoli bolalar"},
	{ID: "43", Name: "Taxt Dastlabki Drift"},
	{ID: "44", Name: "Dragon Raja"},
	{ID: "45", Name: "Xushboʻy Gul Viqor Bilan Gulaydi"},
	{ID: "46", Name: "Xunuk Ammo Kuchli: Busamen G‘alaba Jangi"},
	{ID: "47", Name: "Uzuklar Hukumdori: Rohhirm Urushi"},
	{ID: "48", Name: "Taqdir Jang Kechasi"},
	{ID: "49", Name: "Tahlil Qilish Qobiliyati Bilan Aristokrat Sifatida Qayta Tugʻildim"},
	{ID: "50", Name: "Suv Sehrgari"},
	{ID: "51", Name: "Sirlar Hukmdori"},
	{ID: "52", Name: "Seni oshqozon osti bezingni yemoqchi man"},
	{ID: "53", Name: "Qobilyatsiz Nana"},
	{ID: "54", Name: "Ozga dunyoda yolgiz hujum"},
	{ID: "55", Name: "Osmondagi Janglar"},
	{ID: "56", Name: "Oltin Vaqt"},
	{ID: "57", Name: "Minogra Apokalipsis"},
	{ID: "58", Name: "Men galaktikalar aro imperiyaning yovuz lordiman"},
	{ID: "59", Name: "Mabudlar Hohishi Bilan"},
	{ID: "60", Name: "Lookism"},
	{ID: "61", Name: "Gertsogning qiziga shaxsiy o'qituvchi boʻldim"},
	{ID: "62", Name: "Gachiakuta Qasos"},
	{ID: "63", Name: "Domekano"},
	{ID: "64", Name: "Chegara ortida"},
	{ID: "65", Name: "Bucchgiri"},
	{ID: "66", Name: "AprelYolgoni"},
	{ID: "67", Name: "Afsonaviy ilohy yilnomasi"},
	{ID: "68", Name: "Yettinchi umrni betashvish yashayotgan yovuz ayol"},
	{ID: "69", Name: "Abadiylik qoriqchisi"},
	{ID: "70", Name: "Yana bir narsa soʻrasam boʻladimi"},
	{ID: "71", Name: "O'lim kundaligi"},
	{ID: "72", Name: "Voleybol"},
	{ID: "73", Name: "Shilliq sifatida qayta tug'ilganim haqida"},
	{ID: "74", Name: "Tokyo Gul"},
	{ID: "75", Name: "Horimiya"},
	{ID: "76", Name: "Sarguzashtchilar Restorani"},
	{ID: "77", Name: "Ovoz Shakli"},
	{ID: "78", Name: "Quyon Qiz"},
	{ID: "79", Name: "Bir zarbli odam"},
	{ID: "80", Name: "Hukmdor"},
	{ID: "81", Name: "Yozgi Urushima Tuneli Oldidagi Hayrlashuv"},
	{ID: "82", Name: "Qilich sanati online"},
	{ID: "83", Name: "DMC"},
	{ID: "84", Name: "Ochko'z Berserk"},
	{ID: "85", Name: "Shamolni Bo'ysundirish"},
	{ID: "86", Name: "Saksonolti"},
	{ID: "87", Name: "Dororo"},
	{ID: "88", Name: "Arra Odam"},
	{ID: "89", Name: "Poʻlat qal'adagi kabaneri"},
	{ID: "90", Name: "Rainbow"},
	{ID: "91", Name: "Qo'g'irchoqlar sirki"},
	{ID: "92", Name: "Yulduz Farzandi"},
	{ID: "93", Name: "Elita Sinfi"},
	{ID: "94", Name: "Tajribasiz Senpai"},
	{ID: "95", Name: "Qudratli Soʻngi Dushman"},
	{ID: "96", Name: "Yangi Darvoza"},
	{ID: "97", Name: "Cheksizlikgacha Lv9999"},
	{ID: "98", Name: "Josus X Oilasi"},
	{ID: "99", Name: "Ragnarok Rekordi"},
	{ID: "100", Name: "Sen uchun O'lmas"},
	{ID: "101", Name: "Masamune Qasosi"},
	{ID: "102", Name: "Kim Meni Malika Qildi"},
	{ID: "103", Name: "Koʻk Zindon"},
	{ID: "104", Name: "Parazit - Hayot Saboqlari"},
	{ID: "105", Name: "Uysiz Ma'bud"},
	{ID: "106", Name: "Pari Dumi haqida afsona"},
	{ID: "107", Name: "Kayju 8-Raqam"},
	{ID: "108", Name: "Soqolimni olib, yuqori maktab qizini uyimga olib keldim"},
	{ID: "109", Name: "Yetti O'lim Gunohlari"},
	{ID: "110", Name: "Omadsizning qayta tug'ilishi"},
	{ID: "111", Name: "Qirol oʻyini"},
	{ID: "112", Name: "Violet Evergarden"},
	{ID: "113", Name: "Oʻzga dunyoda darajamni koʻtarib, bu dunyoda ham tengsiz boʻldim"},
	{ID: "114", Name: "Hyouka"},
	{ID: "115", Name: "U qiz yolgiz"},
	{ID: "116", Name: "Bir soatli qizcha"},
	{ID: "117", Name: "Jonli Sana"},
	{ID: "118", Name: "qip-qizil ragna"},
	{ID: "119", Name: "Biz birga bo'lsak, sevgimiz har qanday to'siqni ortda qoldiradi"},
	{ID: "120", Name: "Moviy Quticha"},
	{ID: "121", Name: "Hikaruning songi yozi"},
	{ID: "122", Name: "Taqdir: Buyuk Tartib Mutlaq Iblislar Jabhasi"},
	{ID: "123", Name: "Sevgi deb atalgan shart"},
	{ID: "124", Name: "Afsonaviy qahramonlar va Ruhlar malikasi qizi sifatida qayta tug‘ildim"},
	{ID: "125", Name: "Lideyl Dunyosi"},
	{ID: "126", Name: "Skelet Ritsar o‘zga dunyoda"},
	{ID: "127", Name: "Qora chaqiruvchi"},
	{ID: "128", Name: "Davolash sehridan foydalanishni noto'g'ri usuli"},
	{ID: "129", Name: "Lordi Armiyasining eng kuchli Sehrgari..."},
	{ID: "130", Name: "Tahlil qilish qobiliyatiga ega aristokrat bo'lib qayta tug'ilish"},
	{ID: "131", Name: "Ilohiy qilich maktabining Iblis qilich egasi"},
	{ID: "132", Name: "Meni Qilich bo'lib qayta tug'ilishim haqida"},
	{ID: "133", Name: "O'z joniga qasd qiluvchilar o'zga dunyoda"},
	{ID: "134", Name: "Eng qudratli partiya tomonidan o'limgacha tarbiyalangan Ossan ..."},
	{ID: "135", Name: "Baholovchining mashhur bo'lmagan ishi aslida eng Kuchlisi hisoblanadi"},
	{ID: "136", Name: "Sehr Yaratuvchi Boshqa dunyoda qanday qilib sehr yaratish mumkin"},
	{ID: "137", Name: "O'rta yoshli erkakning zodagon qiziga aylanishi"},
	{ID: "138", Name: "Yaponiyaga Xush Kelibsiz, Elf Xonim!"},
	{ID: "139", Name: "Grimgaldagi kulgi va illuziya"},
	{ID: "140", Name: "Nega hamma meni dunyomni unutdi?"},
	{ID: "141", Name: "80.000 oltin tanga to'plab hayotimni qayta qurdim"},
	{ID: "142", Name: "Cheksiz dendagron"},
	{ID: "143", Name: "Oy sayohati yangi dunyoga olib keladi"},
	{ID: "144", Name: "Man o'rgimchakman ! Ho'sh shunga nma qibti?"},
	{ID: "145", Name: "O'zga dunyoda fermerlik hayotim"},
	{ID: "146", Name: "Iblislar maktabiga hush kelibsiz"},
	{ID: "147", Name: "Daholar uchun oʻzga dunyoda yashash ham muammo emas"},
	{ID: "148", Name: "Shirin renkarnatsiya"},
	{ID: "149", Name: "Menda million hayot bor"},
	{ID: "150", Name: "Maktab tomonidan tan olinmagan iblislar hukmdori"},
	{ID: "151", Name: "Boshqa dunyo bir zumda o'lim kuchiga dosh bera olmaydi"},
	{ID: "152", Name: "Kumush qirolning qayta tugʻilishi"},
	{ID: "153", Name: "Oʻzga dunyoda Noyob mahoratim"},
	{ID: "154", Name: "Egzartis boshqa dunyoda qayta tug'ilib eng kuchli bo'lishga intiladi"},
	{ID: "155", Name: "Nikoh uzuklari haqida afsona"},
	{ID: "156", Name: "tanyang urush yilnomalari"},
	{ID: "157", Name: "Yovuzlik darajasi 99: Men yashirin xo'jayin bo'lishim mumkin, lekin men jin xo'jayini emasman"},
	{ID: "158", Name: "Doktor Eliza: hayotlarni saqlab qoluvchi malika"},
	{ID: "159", Name: "Eng zaif yirtqich hayvon"},
	{ID: "160", Name: "Fojiaga sababchi bõlgan malika xalq uchun qõlidan kelgan barcha ishni qiladi"},
	{ID: "161", Name: "Iblislar hukmdori qoʻshimcha ishda!"},
	{ID: "162", Name: "Oying bilan birga video o'yin"},
	{ID: "163", Name: "Bekami Ko'st Yashashim Ushun Hamma Narsa Qildim"},
	{ID: "164", Name: "Uzoq paladin"},
	{ID: "165", Name: "Realizm qahramoni qirollikni qayta qurishi"},
	{ID: "166", Name: "Olti barg qahramonlari"},
	{ID: "167", Name: "Daho Shifokorning Soyadagi Yangi Hayoti"},
	{ID: "168", Name: "Qayta tugʻilgan aristokratning misli koʻrilmagan sarguzashtlari"},
	{ID: "169", Name: "Sakkizinchi o'g'il qo'ysangizlarchi?"},
	{ID: "170", Name: "O'yindagi Eng Boy odam"},
	{ID: "171", Name: "O'yinsiz hayot yo'q"},
	{ID: "172", Name: "Arifureta: Dunyodagi eng kuchli hunarmand"},
	{ID: "173", Name: "Gildiya adminstratori bo'lib ortiqcha ishlashni xohlamaganim uchun ishdan ketmoqchiman"},
	{ID: "174", Name: "Oddiy insondan qahramonlikkacha"},
	{ID: "175", Name: "Tayoq va qilich"},
	{ID: "176", Name: "Re:Zero"},
	{ID: "177", Name: "Onmyo Qayta Tug‘ilishi: Hayolot Olami"},
	{ID: "178", Name: "Yettinchi shahzoda sifatida qayta tug'ildim va endi sehrimni istaganimcha kuchaytiraman!"},
	{ID: "179", Name: "Mening Qotillik Maqomim Qahramonlik Maqomidan Yaxshiroq"},
	{ID: "180", Name: "Yugurening abadiyligi"},
	{ID: "181", Name: "Daydi itlarning buyugi"},
	{ID: "182", Name: "Meni qizcham nafaqat go'zal"},
	{ID: "183", Name: "Meni qahramonlik akademiyam"},
	{ID: "184", Name: "Barmoqlar uchidagi sevgi"},
	{ID: "185", Name: "Shangri-la chegarasi"},
	{ID: "186", Name: "Kelajak kundaligi"},
	{ID: "187", Name: "Men eng kuchli sarguzashtchi bo'lish uchun har doim mashq qildim"},
	{ID: "188", Name: "Do'stimning singlisi bezovta qilyapti"},
	{ID: "189", Name: "Shikastlanishni istamasdim shuning uchun himoyamni kuchaytirdim"},
	{ID: "190", Name: "Oxirgi Telba Boss paydo bo'ldi"},
	{ID: "191", Name: "Vayron bo'lgan mo'jizalar mamlakati"},
	{ID: "192", Name: "Qahramonning qaytishi"},
	{ID: "193", Name: "Ninja va Yakudza"},
	{ID: "194", Name: "Bosning qizi va uning Enagasi"},
	{ID: "195", Name: "Detektiv allaqchon o'lgan"},
	{ID: "196", Name: "Friren - Soʻnggi manzilga kuzatuvchi"},
	{ID: "197", Name: "Exo Terror"},
	{ID: "198", Name: "Arknayts: Prelyudiya tongga tomon"},
	{ID: "199", Name: "Takt Opus. Taqdir"},
	{ID: "200", Name: "Orient"},
	{ID: "201", Name: "Magic Kaito Kid ID"},
	{ID: "202", Name: "Chitose-kun va ramuna shishasi"},
	{ID: "203", Name: "Zanjirli qul"},
	{ID: "204", Name: "Bo’sani jalb etib"},
	{ID: "205", Name: "Oxirgi Chaqiruvchi"},
	{ID: "206", Name: "Odamlar va Jinlar solnomasi"},
	{ID: "207", Name: "Tamon Qaysi Shaxsiyatta"},
	{ID: "208", Name: "Konan sehrni ko'ra oladigan sehrgar"},
	{ID: "209", Name: "qahramonlikdan vos kechib"},
	{ID: "210", Name: "QORA OY: qonli qurbonxona"},
	{ID: "211", Name: "Qahramonlar sadosi"},
	{ID: "212", Name: "Detektiv allaqachon o'lgan"},
	{ID: "213", Name: "O'zga dunyoda smartfonim bilan"},
	{ID: "214", Name: "Friren So'ngi manzilga kuzatuvchi"},
	{ID: "215", Name: "Anime 215"},
	{ID: "216", Name: "Anime 216"},
	{ID: "217", Name: "Anime 217"},
	{ID: "218", Name: "Anime 218"},
	{ID: "219", Name: "Anime 219"},
	{ID: "220", Name: "Anime 220"},
	{ID: "221", Name: "Anime 221"},
	{ID: "222", Name: "Anime 222"},
	{ID: "223", Name: "Anime 223"},
	{ID: "224", Name: "Anime 224"},
	{ID: "225", Name: "Anime 225"}, // ... barcha 225 ta anime shu yerda
}

func SearchAnime(query string) []SearchResult {
	query = strings.ToLower(strings.TrimSpace(query))
	var matches []SearchResult

	// AnimeList (katta harf bilan) ishlatamiz
	for _, entry := range AnimeList {
		lowerName := strings.ToLower(entry.Name)

		score := levenshtein.ComputeDistance(query, lowerName)
		contains := strings.Contains(lowerName, query)

		if score <= 5 || contains {
			if contains && score > 2 {
				score = 2
			}
			matches = append(matches, SearchResult{
				ID:    entry.ID,
				Name:  entry.Name,
				Score: score,
			})
		}
	}

	sort.Slice(matches, func(i, j int) bool {
		return matches[i].Score < matches[j].Score
	})

	if len(matches) > 8 {
		return matches[:8]
	}
	return matches
}
